@startuml
'----- Table Description ----
'Object Colors Setting
skinparam defaultFontName Arial
skinparam defaultFontSize 12

skinparam rectangle {
    BackgroundColor #87CEFA
    BorderColor #000000
}

legend top
|=        Object  |=           Colors  |
| Microcontroller  |<back:#A0522D>                                    |
| System  |<back:#9370DB>                                    |
| Layer  |<back:#FEE599>                                    |
| Component |<back:#E0FFFF>                                    |
| Module |<back:#E2EFD9>                                    |
| Uint |<back:#7FFFD4>                                    |
| Tiny |<back:#FFC0CB>                                    |
endlegend

package "SYSAD-xxx Software" #9370DB {
    package "SWC" #FEE599 {
        package "SWAD-001 Application" #E0FFFF {
            rectangle "SWAD-001-001\nMain" as Main #E2EFD9
            rectangle "SWAD-001-002\nAPPs Initialization" as AppsInit #E2EFD9
            rectangle "SWAD-001-003\nPinIOs Sensing" as PinIOSensing #E2EFD9
            rectangle "SWAD-001-004\nState Machine" as StateMachine #E2EFD9
            rectangle "SWAD-001-005\nPower Management" as PowerManagement #E2EFD9
            rectangle "SWAD-001-006\nTask and Schedule" as TaskSchedule #E2EFD9
            rectangle "SWAD-001-007\nTasks Config" as TasksConfig #E2EFD9
            rectangle "SWAD-001-008\nClock Source Config" as ClockSourceConfig #E2EFD9
        }
    }

    package "BSW" #FEE599 {
        package "SWAD-002 Service" as Service #E0FFFF {
            rectangle "SWAD-002-001\nUDS" as UDS #E2EFD9
            rectangle "SWAD-002-002\nFuSa" as FuSa #E2EFD9
            rectangle "SWAD-002-003\nSecurity" as Security #E2EFD9
        }

        package "SWAD-003 HAL" as HAL #E0FFFF {
            rectangle "SWAD-003-001\nClock Source Config" as HAL_ClockSourceConfig #E2EFD9
            rectangle "SWAD-003-002\nPinIOs Sensing" as HAL_PinIOSensing #E2EFD9
            rectangle "SWAD-003-003\nPower Config" as HAL_PowerConfig #E2EFD9
        }

        package "SWAD-004 OS" as OS #E0FFFF {
            rectangle "freeRTOS Modules" as freeRTOS #E2EFD9
        }
    }

    package "MCAL" #FEE599 {
        package "SWAD-005 Drivers" as Drivers #E0FFFF {
            rectangle "SWAD-005-001\nClock Source Config" as MCAL_ClockSourceConfig #E2EFD9
            rectangle "SWAD-005-002\nPinIOs Sensing" as MCAL_PinIOSensing #E2EFD9
            rectangle "SWAD-005-003\nPower Config" as MCAL_PowerConfig #E2EFD9
        }
    }
}

rectangle "Microcontroller" as MCU #A0522D

SWC <--> BSW
BSW <--> MCAL
MCAL <--> MCU

@enduml